<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <artifactId>nvx-perf-aep</artifactId>
    <packaging>jar</packaging>
    <name>AEP</name>

    <parent>
        <groupId>com.neeve</groupId>
        <artifactId>nvx-perf-parent</artifactId>
        <version>3.16-SNAPSHOT</version>
    </parent>

    <properties>
        <nvx.robin.version>3.0.22</nvx.robin.version>
    </properties>

    <dependencies>
        <dependency>
            <groupId>com.neeve</groupId>
            <artifactId>nvx-perf-common</artifactId>
            <version>${project.version}</version>
        </dependency>

        <dependency>
            <groupId>com.neeve</groupId>
            <artifactId>nvx-perf-models</artifactId>
            <version>${project.version}</version>
        </dependency>

        <dependency>
            <groupId>com.neeve</groupId>
            <artifactId>nvx-perf-serialization</artifactId>
            <version>${project.version}</version>
        </dependency>

        <dependency>
            <groupId>org.apache.poi</groupId>
            <artifactId>poi-ooxml</artifactId>
            <version>5.1.0</version>
            <exclusions>
                <exclusion>
                    <groupId>commons-logging</groupId>
                    <artifactId>commons-logging</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>com.neeve</groupId>
                <artifactId>nvx-adm-maven-plugin</artifactId>
                <version>${nvx.talon.version}</version>
                <executions>
                    <execution>
                        <id>Messages</id>
                        <phase>generate-sources</phase>
                        <goals>
                            <goal>adm-generate</goal>
                        </goals>
                        <configuration>
                            <modelFile>${project.basedir}/src/main/models/com/neeve/perf/aep/engine/messages/model.xml</modelFile>
                            <encodingType>Xbuf2</encodingType>
                        </configuration>
                    </execution>

                    <execution>
                        <id>State</id>
                        <phase>generate-sources</phase>
                        <goals>
                            <goal>adm-generate</goal>
                        </goals>
                        <configuration>
                            <modelFile>${project.basedir}/src/main/models/com/neeve/perf/aep/engine/state/model.xml</modelFile>
                            <encodingType>Xbuf2</encodingType>
                        </configuration>
                    </execution>
                </executions>
            </plugin>

            <plugin>
                <groupId>com.neeve</groupId>
                <artifactId>nvx-robin-maven-plugin</artifactId>
                <version>${nvx.robin.version}</version>
                <executions>
                    <execution>
                        <id>Xar</id>
                        <phase>package</phase>
                        <goals>
                            <goal>xar</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>
</project>
