<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <artifactId>nvx-perf-dist</artifactId>
    <packaging>pom</packaging>
    <name>Distribution</name>

    <parent>
        <groupId>com.neeve</groupId>
        <artifactId>nvx-perf-parent</artifactId>
        <version>3.16-SNAPSHOT</version>
    </parent>

    <dependencies>
        <!-- Include all perf modules -->
        <dependency>
            <groupId>com.neeve</groupId>
            <artifactId>nvx-perf-common</artifactId>
            <version>${project.version}</version>
        </dependency>

        <dependency>
            <groupId>com.neeve</groupId>
            <artifactId>nvx-perf-time</artifactId>
            <version>${project.version}</version>
        </dependency>

        <dependency>
            <groupId>com.neeve</groupId>
            <artifactId>nvx-perf-models</artifactId>
            <version>${project.version}</version>
        </dependency>

        <dependency>
            <groupId>com.neeve</groupId>
            <artifactId>nvx-perf-serialization</artifactId>
            <version>${project.version}</version>
        </dependency>

        <dependency>
            <groupId>com.neeve</groupId>
            <artifactId>nvx-perf-link</artifactId>
            <version>${project.version}</version>
        </dependency>

        <dependency>
            <groupId>com.neeve</groupId>
            <artifactId>nvx-perf-messaging</artifactId>
            <version>${project.version}</version>
        </dependency>

        <dependency>
            <groupId>com.neeve</groupId>
            <artifactId>nvx-perf-persistence</artifactId>
            <version>${project.version}</version>
        </dependency>

        <dependency>
            <groupId>com.neeve</groupId>
            <artifactId>nvx-perf-storage</artifactId>
            <version>${project.version}</version>
        </dependency>

        <dependency>
            <groupId>com.neeve</groupId>
            <artifactId>nvx-perf-aep</artifactId>
            <version>${project.version}</version>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-dependency-plugin</artifactId>
                <version>2.5</version>
                <executions>
                    <execution>
                        <phase>package</phase>
                        <goals>
                            <goal>copy-dependencies</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>

    <profiles>
        <profile>
            <id>linux-x86-64</id>
            <dependencies>
                <dependency>
                    <groupId>com.neeve</groupId>
                    <artifactId>nvx-native</artifactId>
                    <classifier>linux-x86-64</classifier>
                    <version>${nvx.native.version}</version>
                </dependency>
            </dependencies>

            <build>
                <plugins>
                    <plugin>
                        <artifactId>maven-assembly-plugin</artifactId>
                        <version>2.4</version>
                        <inherited>false</inherited>
                        <executions>
                            <execution>
                                <id>dist-linux-x86-64</id>
                                <phase>package</phase>
                                <goals>
                                    <goal>single</goal>
                                </goals>
                                <inherited>false</inherited>
                                <configuration>
                                    <attach>true</attach>
                                    <tarLongFileMode>gnu</tarLongFileMode>
                                    <descriptor>distribution-linux-x86-64.xml</descriptor>
                                </configuration>
                            </execution>
                        </executions>
                    </plugin>
                </plugins>
            </build>
        </profile>

        <profile>
            <id>osx-x86-64</id>
            <build>
                <plugins>
                    <plugin>
                        <artifactId>maven-assembly-plugin</artifactId>
                        <version>2.4</version>
                        <inherited>false</inherited>
                        <executions>
                            <execution>
                                <id>dist-osx-x86-64</id>
                                <phase>package</phase>
                                <goals>
                                    <goal>single</goal>
                                </goals>
                                <inherited>false</inherited>
                                <configuration>
                                    <attach>true</attach>
                                    <tarLongFileMode>gnu</tarLongFileMode>
                                    <descriptor>distribution-osx-x86-64.xml</descriptor>
                                </configuration>
                            </execution>
                        </executions>
                    </plugin>
                </plugins>
            </build>
        </profile>

        <profile>
            <id>win-x86-64</id>
            <build>
                <plugins>
                    <plugin>
                        <artifactId>maven-assembly-plugin</artifactId>
                        <version>2.4</version>
                        <inherited>false</inherited>
                        <executions>
                            <execution>
                                <id>dist-win-x86-64</id>
                                <phase>package</phase>
                                <goals>
                                    <goal>single</goal>
                                </goals>
                                <inherited>false</inherited>
                                <configuration>
                                    <attach>true</attach>
                                    <tarLongFileMode>gnu</tarLongFileMode>
                                    <descriptor>distribution-win-x86-64.xml</descriptor>
                                </configuration>
                            </execution>
                        </executions>
                    </plugin>
                </plugins>
            </build>
        </profile>
    </profiles>
</project>
